# Copyright 2021 iLogtail Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "example_config/**"
      - "docker/**"
      - "k8s_template/**"
      - "changes/**"
      - "licenses/**"
      - "CHANGELOG.md"
  push:
    branches:
      - main
      - 1.*
      - 2.*

jobs:
  Build:
    runs-on: ${{ matrix.runner }}-latest
    timeout-minutes: 60
    strategy:
      matrix:
        runner: [ubuntu]
      fail-fast: true
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.10

      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set custom submodule URL and fetch
        run: |
          SUBMODULE_PATH="core/_thirdparty/coolbpf"
          git config submodule.$SUBMODULE_PATH.url "https://github.com/aliyun/coolbpf.git"
          git submodule update --init
          cd $SUBMODULE_PATH
          echo "Current commit: $(git rev-parse HEAD)"

      - name: Build Binary
        env:
          BUILD_LOGTAIL_UT: OFF
          ENABLE_COMPATIBLE_MODE: ON
          ENABLE_STATIC_LINK_CRT: ON
          WITHOUTGDB: ON
          MAKE_JOBS: 16
        run: make dist

      - name: Build Docker
        run: make docker

      - name: Push Docker image
        run: |
          docker images
          docker login -u 2237982184@qq.com -p Aa1798826054526 registry.cn-shenzhen.aliyuncs.com/xdownload
          docker tag aliyun/loongcollector:3.1.4 registry.cn-shenzhen.aliyuncs.com/xdownload/loongcollector:3.1.4-custom
          docker push registry.cn-shenzhen.aliyuncs.com/xdownload/loongcollector:3.1.4-custom

  actions-timeline:
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: Kesin11/actions-timeline@v2
